//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGIV.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactosProveedor
    {
        public int idContacto { get; set; }
        public string nombresContacto { get; set; }
        public string ApellidosContacto { get; set; }
        public string cargoContacto { get; set; }
        public string telefonoContacto { get; set; }
        public string eMailContacto { get; set; }
        public string observacion { get; set; }
        public int idProveedor { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
        public virtual Proveedores Proveedores1 { get; set; }
        public virtual Proveedores Proveedores2 { get; set; }
        public virtual Proveedores Proveedores3 { get; set; }
        public virtual Proveedores Proveedores4 { get; set; }
    }
}
