//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGIV.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesPedidos
    {
        public int idDetallep { get; set; }
        public int idProductoNuevo { get; set; }
        public int idPedido { get; set; }
        public int cantidad { get; set; }
        public decimal precioUnidad { get; set; }
        public decimal descuetoUnidad { get; set; }
        public string comentarios { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
        public virtual ProductosNuevos ProductosNuevos { get; set; }
    }
}
