//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGIV.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoDireccion
    {
        public int EmpleadoDireccion1 { get; set; }
        public string Linea1 { get; set; }
        public string Linea2 { get; set; }
        public Nullable<int> idEmpleado { get; set; }
        public Nullable<int> idDireccion { get; set; }
    
        public virtual Direcciones Direcciones { get; set; }
        public virtual Direcciones Direcciones1 { get; set; }
        public virtual Direcciones Direcciones2 { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Empleados Empleados1 { get; set; }
    }
}
