//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGIV.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedoresDireccion
    {
        public int idProveedoresDireccion { get; set; }
        public string Linea1 { get; set; }
        public string Linea2 { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public string codigoPostal { get; set; }
        public Nullable<int> idDistrito { get; set; }
    
        public virtual Distritos Distritos { get; set; }
    }
}
