//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGIV.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransaccionesPago
    {
        public int idTransaccion { get; set; }
        public Nullable<int> idFactura { get; set; }
        public Nullable<int> idTipoPago { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<System.DateTime> fechaTransaccion { get; set; }
    
        public virtual Facturas Facturas { get; set; }
        public virtual TiposPago TiposPago { get; set; }
    }
}
